global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'galadhari-client-server'
    static_configs:
      - targets: ['20.216.4.110:9100']
        labels:
           hostname: 'app-auraa'